language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/src/.vuepress/dist
  github_token: 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
  keep_history: true
  on:
    branch: master
